export const DUMMY_CONSTANTS = {
  LAST_UPDATED: "2025-08-07T00:00:00Z",
  ACMA_OUTAGES: 3120,
  ONGOING_ACMA_OUTAGES: 15,
  UNPLANNED_OUTAGES: 139012,
  OUTAGES: [
    {
      incidentId: "INC100001",
      communicationId: "COM200001",
      status: "Active",
      type: "major-outages",
      severity: "major",
      stage: "stage-2",
      region: "Sydney, NSW",
      identifiedAt: "2025-10-10T03:15:00Z",
      lastUpdate: "2025-10-15T01:00:00Z",
      title: "Sydney CBD Fiber Cut",
      description:
        "A major fiber cable was accidentally cut during roadworks, causing widespread internet disruption in the CBD.",
      causeOfOutage: "Fiber cable cut by construction",
      totalAffected: 12000,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-10T03:15:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 12000,
        },
        {
          status: "Outage update issued",
          time: "2025-10-12T08:00:00Z",
          stage: "stage-2",
          severity: "major",
          affected: 9000,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-12T08:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-10-12T08:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-10-12T08:15:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-12T08:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100002",
      communicationId: "COM200002",
      status: "Resolved",
      type: "significant-outages",
      severity: "significant",
      stage: "resolved",
      region: "Melbourne, VIC",
      identifiedAt: "2025-09-28T14:30:00Z",
      lastUpdate: "2025-10-01T09:00:00Z",
      title: "Melbourne Data Center Cooling Failure",
      description:
        "A cooling system malfunction led to overheating and partial shutdown of the main data center.",
      causeOfOutage: "Cooling system failure",
      totalAffected: 3500,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-09-28T14:30:00Z",
          stage: "stage-1",
          severity: "significant",
          consumers: 3500,
        },
        {
          status: "Outage update issued",
          time: "2025-09-29T10:00:00Z",
          stage: "stage-2",
          severity: "significant",
          affected: 1200,
          commsCompliance: [
            { channel: "Email comms", time: "2025-09-29T10:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-09-29T10:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-09-29T10:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-09-29T10:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-10-01T09:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100003",
      communicationId: "COM200003",
      status: "Active",
      type: "new-outages",
      severity: "significant",
      stage: "stage-1",
      region: "Brisbane, QLD",
      identifiedAt: "2025-10-14T06:45:00Z",
      lastUpdate: "2025-10-15T00:30:00Z",
      title: "Brisbane Power Substation Fire",
      description:
        "A fire at a local power substation caused a loss of connectivity for several suburbs.",
      causeOfOutage: "Substation fire",
      totalAffected: 4200,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-14T06:45:00Z",
          stage: "stage-1",
          severity: "significant",
          consumers: 4200,
        },
        {
          status: "Outage update issued",
          time: "2025-10-14T12:00:00Z",
          stage: "stage-1",
          severity: "significant",
          affected: 4200,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-14T12:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-10-14T12:10:00Z", complete: false },
            { channel: "Spatial Buzz", time: "2025-10-14T12:15:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-14T12:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100004",
      communicationId: "COM200004",
      status: "Resolved",
      type: "exceeding-slo-sla",
      severity: "major",
      stage: "resolved",
      region: "Perth, WA",
      identifiedAt: "2025-09-20T11:00:00Z",
      lastUpdate: "2025-09-21T15:00:00Z",
      title: "Perth Exchange Flooding",
      description:
        "Heavy rainfall caused flooding in the main exchange, disrupting services for thousands.",
      causeOfOutage: "Flooding due to heavy rain",
      totalAffected: 8000,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-09-20T11:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 8000,
        },
        {
          status: "Outage update issued",
          time: "2025-09-20T18:00:00Z",
          stage: "stage-2",
          severity: "major",
          affected: 5000,
          commsCompliance: [
            { channel: "Email comms", time: "2025-09-20T18:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-09-20T18:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-09-20T18:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-09-20T18:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-09-21T15:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100005",
      communicationId: "COM200005",
      status: "Active",
      type: "major-outages",
      severity: "major",
      stage: "stage-2",
      region: "Adelaide, SA",
      identifiedAt: "2025-10-13T04:00:00Z",
      lastUpdate: "2025-10-15T01:00:00Z",
      title: "Adelaide Backbone Router Failure",
      description:
        "A critical backbone router failed, causing major connectivity issues across the city.",
      causeOfOutage: "Router hardware failure",
      totalAffected: 9500,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-13T04:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 9500,
        },
        {
          status: "Outage update issued",
          time: "2025-10-13T10:00:00Z",
          stage: "stage-2",
          severity: "major",
          affected: 7000,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-13T10:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-10-13T10:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-10-13T10:15:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-13T10:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100006",
      communicationId: "COM200006",
      status: "Resolved",
      type: "significant-outages",
      severity: "significant",
      stage: "resolved",
      region: "Hobart, TAS",
      identifiedAt: "2025-09-15T07:30:00Z",
      lastUpdate: "2025-09-16T12:00:00Z",
      title: "Hobart Network Latency",
      description: "A misconfigured switch led to high latency and packet loss for many users.",
      causeOfOutage: "Switch misconfiguration",
      totalAffected: 2100,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-09-15T07:30:00Z",
          stage: "stage-1",
          severity: "significant",
          consumers: 2100,
        },
        {
          status: "Outage update issued",
          time: "2025-09-15T15:00:00Z",
          stage: "stage-2",
          severity: "significant",
          affected: 800,
          commsCompliance: [
            { channel: "Email comms", time: "2025-09-15T15:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-09-15T15:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-09-15T15:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-09-15T15:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-09-16T12:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100007",
      communicationId: "COM200007",
      status: "Active",
      type: "new-outages",
      severity: "major",
      stage: "stage-1",
      region: "Canberra, ACT",
      identifiedAt: "2025-10-15T05:00:00Z",
      lastUpdate: "2025-10-15T05:30:00Z",
      title: "Canberra DDoS Attack",
      description:
        "A distributed denial-of-service attack is causing intermittent outages in the ACT region.",
      causeOfOutage: "DDoS attack",
      totalAffected: 6000,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-15T05:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 6000,
        },
        {
          status: "Outage update issued",
          time: "2025-10-15T05:15:00Z",
          stage: "stage-1",
          severity: "major",
          affected: 6000,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-15T05:16:00Z", complete: false },
            { channel: "SMS comms", time: "2025-10-15T05:17:00Z", complete: false },
            { channel: "Spatial Buzz", time: "2025-10-15T05:18:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-15T05:19:00Z", complete: false },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100008",
      communicationId: "COM200008",
      status: "Resolved",
      type: "exceeding-slo-sla",
      severity: "significant",
      stage: "resolved",
      region: "Gold Coast, QLD",
      identifiedAt: "2025-09-10T09:00:00Z",
      lastUpdate: "2025-09-12T10:00:00Z",
      title: "Gold Coast Scheduled Maintenance Overrun",
      description: "Scheduled maintenance exceeded the planned window, causing extended downtime.",
      causeOfOutage: "Maintenance overrun",
      totalAffected: 1800,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-09-10T09:00:00Z",
          stage: "stage-1",
          severity: "significant",
          consumers: 1800,
        },
        {
          status: "Outage update issued",
          time: "2025-09-11T08:00:00Z",
          stage: "stage-2",
          severity: "significant",
          affected: 500,
          commsCompliance: [
            { channel: "Email comms", time: "2025-09-11T08:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-09-11T08:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-09-11T08:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-09-11T08:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-09-12T10:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100009",
      communicationId: "COM200009",
      status: "Active",
      type: "major-outages",
      severity: "major",
      stage: "stage-2",
      region: "Darwin, NT",
      identifiedAt: "2025-10-12T02:00:00Z",
      lastUpdate: "2025-10-15T01:00:00Z",
      title: "Darwin Satellite Link Failure",
      description: "A satellite link failure has isolated several remote communities.",
      causeOfOutage: "Satellite link failure",
      totalAffected: 2500,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-12T02:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 2500,
        },
        {
          status: "Outage update issued",
          time: "2025-10-13T09:00:00Z",
          stage: "stage-2",
          severity: "major",
          affected: 1200,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-13T09:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-10-13T09:10:00Z", complete: false },
            { channel: "Spatial Buzz", time: "2025-10-13T09:15:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-13T09:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100010",
      communicationId: "COM200010",
      status: "Resolved",
      type: "significant-outages",
      severity: "significant",
      stage: "resolved",
      region: "Wollongong, NSW",
      identifiedAt: "2025-09-05T13:00:00Z",
      lastUpdate: "2025-09-06T10:00:00Z",
      title: "Wollongong Node Overload",
      description: "A sudden surge in demand overloaded a key node, causing service interruptions.",
      causeOfOutage: "Node overload",
      totalAffected: 1700,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-09-05T13:00:00Z",
          stage: "stage-1",
          severity: "significant",
          consumers: 1700,
        },
        {
          status: "Outage update issued",
          time: "2025-09-05T18:00:00Z",
          stage: "stage-2",
          severity: "significant",
          affected: 400,
          commsCompliance: [
            { channel: "Email comms", time: "2025-09-05T18:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-09-05T18:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-09-05T18:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-09-05T18:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-09-06T10:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100011",
      communicationId: "COM200011",
      status: "Active",
      type: "new-outages",
      severity: "significant",
      stage: "stage-1",
      region: "Newcastle, NSW",
      identifiedAt: "2025-10-14T07:30:00Z",
      lastUpdate: "2025-10-15T01:00:00Z",
      title: "Newcastle Exchange Power Loss",
      description:
        "A power outage at the main exchange has disrupted services in the Newcastle area.",
      causeOfOutage: "Power outage",
      totalAffected: 3200,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-14T07:30:00Z",
          stage: "stage-1",
          severity: "significant",
          consumers: 3200,
        },
        {
          status: "Outage update issued",
          time: "2025-10-14T12:00:00Z",
          stage: "stage-1",
          severity: "significant",
          affected: 3200,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-14T12:05:00Z", complete: false },
            { channel: "SMS comms", time: "2025-10-14T12:10:00Z", complete: false },
            { channel: "Spatial Buzz", time: "2025-10-14T12:15:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-14T12:20:00Z", complete: false },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100012",
      communicationId: "COM200012",
      status: "Resolved",
      type: "exceeding-slo-sla",
      severity: "major",
      stage: "resolved",
      region: "Geelong, VIC",
      identifiedAt: "2025-09-01T10:00:00Z",
      lastUpdate: "2025-09-02T09:00:00Z",
      title: "Geelong Fiber Splice Delay",
      description: "A delay in fiber splicing extended the outage window for Geelong customers.",
      causeOfOutage: "Fiber splicing delay",
      totalAffected: 900,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-09-01T10:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 900,
        },
        {
          status: "Outage update issued",
          time: "2025-09-01T18:00:00Z",
          stage: "stage-2",
          severity: "major",
          affected: 200,
          commsCompliance: [
            { channel: "Email comms", time: "2025-09-01T18:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-09-01T18:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-09-01T18:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-09-01T18:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-09-02T09:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100013",
      communicationId: "COM200013",
      status: "Active",
      type: "major-outages",
      severity: "major",
      stage: "stage-2",
      region: "Ballarat, VIC",
      identifiedAt: "2025-10-13T03:00:00Z",
      lastUpdate: "2025-10-15T01:00:00Z",
      title: "Ballarat Main Switch Failure",
      description: "A main switch failure has caused a blackout in the Ballarat region.",
      causeOfOutage: "Switch failure",
      totalAffected: 2100,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-13T03:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 2100,
        },
        {
          status: "Outage update issued",
          time: "2025-10-13T09:00:00Z",
          stage: "stage-2",
          severity: "major",
          affected: 900,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-13T09:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-10-13T09:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-10-13T09:15:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-13T09:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100014",
      communicationId: "COM200014",
      status: "Resolved",
      type: "significant-outages",
      severity: "significant",
      stage: "resolved",
      region: "Cairns, QLD",
      identifiedAt: "2025-08-25T11:00:00Z",
      lastUpdate: "2025-08-26T08:00:00Z",
      title: "Cairns Wireless Tower Outage",
      description: "A wireless tower malfunction caused loss of service in northern Cairns.",
      causeOfOutage: "Tower malfunction",
      totalAffected: 600,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-08-25T11:00:00Z",
          stage: "stage-1",
          severity: "significant",
          consumers: 600,
        },
        {
          status: "Outage update issued",
          time: "2025-08-25T16:00:00Z",
          stage: "stage-2",
          severity: "significant",
          affected: 200,
          commsCompliance: [
            { channel: "Email comms", time: "2025-08-25T16:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-08-25T16:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-08-25T16:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-08-25T16:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-08-26T08:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100015",
      communicationId: "COM200015",
      status: "Active",
      type: "new-outages",
      severity: "major",
      stage: "stage-1",
      region: "Toowoomba, QLD",
      identifiedAt: "2025-10-15T06:00:00Z",
      lastUpdate: "2025-10-15T06:30:00Z",
      title: "Toowoomba ServiceNow Integration Issue",
      description:
        "A ServiceNow integration failure is preventing incident updates from being processed.",
      causeOfOutage: "ServiceNow integration failure",
      totalAffected: 1100,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-15T06:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 1100,
        },
        {
          status: "Outage update issued",
          time: "2025-10-15T06:15:00Z",
          stage: "stage-1",
          severity: "major",
          affected: 1100,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-15T06:16:00Z", complete: false },
            { channel: "SMS comms", time: "2025-10-15T06:17:00Z", complete: false },
            { channel: "Spatial Buzz", time: "2025-10-15T06:18:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-15T06:19:00Z", complete: false },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100016",
      communicationId: "COM200016",
      status: "Resolved",
      type: "exceeding-slo-sla",
      severity: "significant",
      stage: "resolved",
      region: "Shepparton, VIC",
      identifiedAt: "2025-08-20T10:00:00Z",
      lastUpdate: "2025-08-21T09:00:00Z",
      title: "Shepparton Scheduled Upgrade Delay",
      description: "A scheduled upgrade took longer than expected, causing extended downtime.",
      causeOfOutage: "Upgrade delay",
      totalAffected: 700,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-08-20T10:00:00Z",
          stage: "stage-1",
          severity: "significant",
          consumers: 700,
        },
        {
          status: "Outage update issued",
          time: "2025-08-20T18:00:00Z",
          stage: "stage-2",
          severity: "significant",
          affected: 200,
          commsCompliance: [
            { channel: "Email comms", time: "2025-08-20T18:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-08-20T18:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-08-20T18:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-08-20T18:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-08-21T09:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100017",
      communicationId: "COM200017",
      status: "Active",
      type: "major-outages",
      severity: "major",
      stage: "stage-2",
      region: "Mackay, QLD",
      identifiedAt: "2025-10-13T02:00:00Z",
      lastUpdate: "2025-10-15T01:00:00Z",
      title: "Mackay Main Fiber Disruption",
      description: "A main fiber line was damaged by severe weather, causing outages in Mackay.",
      causeOfOutage: "Severe weather",
      totalAffected: 1800,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-13T02:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 1800,
        },
        {
          status: "Outage update issued",
          time: "2025-10-13T08:00:00Z",
          stage: "stage-2",
          severity: "major",
          affected: 900,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-13T08:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-10-13T08:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-10-13T08:15:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-13T08:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100018",
      communicationId: "COM200018",
      status: "Resolved",
      type: "significant-outages",
      severity: "significant",
      stage: "resolved",
      region: "Rockhampton, QLD",
      identifiedAt: "2025-08-15T09:00:00Z",
      lastUpdate: "2025-08-16T08:00:00Z",
      title: "Rockhampton Node Failure",
      description: "A node failure caused a temporary loss of service in Rockhampton.",
      causeOfOutage: "Node hardware failure",
      totalAffected: 400,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-08-15T09:00:00Z",
          stage: "stage-1",
          severity: "significant",
          consumers: 400,
        },
        {
          status: "Outage update issued",
          time: "2025-08-15T14:00:00Z",
          stage: "stage-2",
          severity: "significant",
          affected: 100,
          commsCompliance: [
            { channel: "Email comms", time: "2025-08-15T14:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-08-15T14:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-08-15T14:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-08-15T14:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-08-16T08:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100019",
      communicationId: "COM200019",
      status: "Active",
      type: "new-outages",
      severity: "major",
      stage: "stage-1",
      region: "Bendigo, VIC",
      identifiedAt: "2025-10-15T07:00:00Z",
      lastUpdate: "2025-10-15T07:30:00Z",
      title: "Bendigo Service Interruption",
      description: "A configuration error caused a service interruption for Bendigo customers.",
      causeOfOutage: "Configuration error",
      totalAffected: 900,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-15T07:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 900,
        },
        {
          status: "Outage update issued",
          time: "2025-10-15T07:15:00Z",
          stage: "stage-1",
          severity: "major",
          affected: 900,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-15T07:16:00Z", complete: false },
            { channel: "SMS comms", time: "2025-10-15T07:17:00Z", complete: false },
            { channel: "Spatial Buzz", time: "2025-10-15T07:18:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-15T07:19:00Z", complete: false },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100020",
      communicationId: "COM200020",
      status: "Resolved",
      type: "exceeding-slo-sla",
      severity: "significant",
      stage: "resolved",
      region: "Sunshine Coast, QLD",
      identifiedAt: "2025-08-10T08:00:00Z",
      lastUpdate: "2025-08-11T07:00:00Z",
      title: "Sunshine Coast Planned Outage Overrun",
      description:
        "A planned outage overran its scheduled window, affecting more customers than anticipated.",
      causeOfOutage: "Planned outage overrun",
      totalAffected: 500,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-08-10T08:00:00Z",
          stage: "stage-1",
          severity: "significant",
          consumers: 500,
        },
        {
          status: "Outage update issued",
          time: "2025-08-10T14:00:00Z",
          stage: "stage-2",
          severity: "significant",
          affected: 100,
          commsCompliance: [
            { channel: "Email comms", time: "2025-08-10T14:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-08-10T14:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-08-10T14:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-08-10T14:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-08-11T07:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100021",
      communicationId: "COM200021",
      status: "Active",
      type: "major-outages",
      severity: "major",
      stage: "stage-2",
      region: "Launceston, TAS",
      identifiedAt: "2025-10-12T01:00:00Z",
      lastUpdate: "2025-10-15T01:00:00Z",
      title: "Launceston Main Exchange Outage",
      description: "A main exchange outage is affecting connectivity in Launceston.",
      causeOfOutage: "Exchange hardware failure",
      totalAffected: 1300,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-12T01:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 1300,
        },
        {
          status: "Outage update issued",
          time: "2025-10-12T07:00:00Z",
          stage: "stage-2",
          severity: "major",
          affected: 700,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-12T07:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-10-12T07:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-10-12T07:15:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-12T07:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100022",
      communicationId: "COM200022",
      status: "Resolved",
      type: "significant-outages",
      severity: "significant",
      stage: "resolved",
      region: "Port Macquarie, NSW",
      identifiedAt: "2025-08-05T10:00:00Z",
      lastUpdate: "2025-08-06T09:00:00Z",
      title: "Port Macquarie Fiber Break",
      description: "A fiber break caused by nearby construction led to a temporary outage.",
      causeOfOutage: "Construction accident",
      totalAffected: 400,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-08-05T10:00:00Z",
          stage: "stage-1",
          severity: "significant",
          consumers: 400,
        },
        {
          status: "Outage update issued",
          time: "2025-08-05T14:00:00Z",
          stage: "stage-2",
          severity: "significant",
          affected: 100,
          commsCompliance: [
            { channel: "Email comms", time: "2025-08-05T14:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-08-05T14:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-08-05T14:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-08-05T14:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-08-06T09:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100023",
      communicationId: "COM200023",
      status: "Active",
      type: "new-outages",
      severity: "major",
      stage: "stage-1",
      region: "Bathurst, NSW",
      identifiedAt: "2025-10-15T08:00:00Z",
      lastUpdate: "2025-10-15T08:30:00Z",
      title: "Bathurst Service Disruption",
      description: "A software update caused unexpected service disruption in Bathurst.",
      causeOfOutage: "Software update error",
      totalAffected: 600,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-15T08:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 600,
        },
        {
          status: "Outage update issued",
          time: "2025-10-15T08:15:00Z",
          stage: "stage-1",
          severity: "major",
          affected: 600,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-15T08:16:00Z", complete: false },
            { channel: "SMS comms", time: "2025-10-15T08:17:00Z", complete: false },
            { channel: "Spatial Buzz", time: "2025-10-15T08:18:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-15T08:19:00Z", complete: false },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100024",
      communicationId: "COM200024",
      status: "Resolved",
      type: "exceeding-slo-sla",
      severity: "major",
      stage: "resolved",
      region: "Orange, NSW",
      identifiedAt: "2025-08-01T09:00:00Z",
      lastUpdate: "2025-08-02T08:00:00Z",
      title: "Orange Planned Maintenance Delay",
      description: "Planned maintenance took longer than expected, causing extended downtime.",
      causeOfOutage: "Maintenance delay",
      totalAffected: 300,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-08-01T09:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 300,
        },
        {
          status: "Outage update issued",
          time: "2025-08-01T14:00:00Z",
          stage: "stage-2",
          severity: "major",
          affected: 100,
          commsCompliance: [
            { channel: "Email comms", time: "2025-08-01T14:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-08-01T14:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-08-01T14:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-08-01T14:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-08-02T08:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100025",
      communicationId: "COM200025",
      status: "Active",
      type: "major-outages",
      severity: "major",
      stage: "stage-2",
      region: "Dubbo, NSW",
      identifiedAt: "2025-10-13T01:00:00Z",
      lastUpdate: "2025-10-15T01:00:00Z",
      title: "Dubbo Main Router Outage",
      description: "A main router outage is affecting Dubbo and surrounding areas.",
      causeOfOutage: "Router hardware failure",
      totalAffected: 1100,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-13T01:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 1100,
        },
        {
          status: "Outage update issued",
          time: "2025-10-13T07:00:00Z",
          stage: "stage-2",
          severity: "major",
          affected: 600,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-13T07:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-10-13T07:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-10-13T07:15:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-13T07:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100026",
      communicationId: "COM200026",
      status: "Resolved",
      type: "significant-outages",
      severity: "significant",
      stage: "resolved",
      region: "Wagga Wagga, NSW",
      identifiedAt: "2025-07-25T10:00:00Z",
      lastUpdate: "2025-07-26T09:00:00Z",
      title: "Wagga Wagga Fiber Cut",
      description: "A fiber cut caused by nearby excavation led to a temporary outage.",
      causeOfOutage: "Excavation accident",
      totalAffected: 400,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-07-25T10:00:00Z",
          stage: "stage-1",
          severity: "significant",
          consumers: 400,
        },
        {
          status: "Outage update issued",
          time: "2025-07-25T14:00:00Z",
          stage: "stage-2",
          severity: "significant",
          affected: 100,
          commsCompliance: [
            { channel: "Email comms", time: "2025-07-25T14:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-07-25T14:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-07-25T14:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-07-25T14:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-07-26T09:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100027",
      communicationId: "COM200027",
      status: "Active",
      type: "new-outages",
      severity: "major",
      stage: "stage-1",
      region: "Mildura, VIC",
      identifiedAt: "2025-10-15T09:00:00Z",
      lastUpdate: "2025-10-15T09:30:00Z",
      title: "Mildura Service Disruption",
      description: "A software bug caused a temporary service disruption in Mildura.",
      causeOfOutage: "Software bug",
      totalAffected: 500,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-15T09:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 500,
        },
        {
          status: "Outage update issued",
          time: "2025-10-15T09:15:00Z",
          stage: "stage-1",
          severity: "major",
          affected: 500,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-15T09:16:00Z", complete: false },
            { channel: "SMS comms", time: "2025-10-15T09:17:00Z", complete: false },
            { channel: "Spatial Buzz", time: "2025-10-15T09:18:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-15T09:19:00Z", complete: false },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100028",
      communicationId: "COM200028",
      status: "Resolved",
      type: "exceeding-slo-sla",
      severity: "significant",
      stage: "resolved",
      region: "Albury, NSW",
      identifiedAt: "2025-07-20T09:00:00Z",
      lastUpdate: "2025-07-21T08:00:00Z",
      title: "Albury Planned Outage Overrun",
      description:
        "A planned outage overran its scheduled window, affecting more customers than anticipated.",
      causeOfOutage: "Planned outage overrun",
      totalAffected: 300,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-07-20T09:00:00Z",
          stage: "stage-1",
          severity: "significant",
          consumers: 300,
        },
        {
          status: "Outage update issued",
          time: "2025-07-20T14:00:00Z",
          stage: "stage-2",
          severity: "significant",
          affected: 100,
          commsCompliance: [
            { channel: "Email comms", time: "2025-07-20T14:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-07-20T14:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-07-20T14:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-07-20T14:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-07-21T08:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100029",
      communicationId: "COM200029",
      status: "Active",
      type: "major-outages",
      severity: "major",
      stage: "stage-2",
      region: "Nowra, NSW",
      identifiedAt: "2025-10-13T00:00:00Z",
      lastUpdate: "2025-10-15T01:00:00Z",
      title: "Nowra Main Switch Outage",
      description: "A main switch outage is affecting Nowra and nearby areas.",
      causeOfOutage: "Switch hardware failure",
      totalAffected: 800,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-10-13T00:00:00Z",
          stage: "stage-1",
          severity: "major",
          consumers: 800,
        },
        {
          status: "Outage update issued",
          time: "2025-10-13T06:00:00Z",
          stage: "stage-2",
          severity: "major",
          affected: 400,
          commsCompliance: [
            { channel: "Email comms", time: "2025-10-13T06:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-10-13T06:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-10-13T06:15:00Z", complete: false },
            { channel: "ServiceNow", time: "2025-10-13T06:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
    {
      incidentId: "INC100030",
      communicationId: "COM200030",
      status: "Resolved",
      type: "significant-outages",
      severity: "significant",
      stage: "resolved",
      region: "Lismore, NSW",
      identifiedAt: "2025-07-15T08:00:00Z",
      lastUpdate: "2025-07-16T07:00:00Z",
      title: "Lismore Node Failure",
      description: "A node failure caused a temporary loss of service in Lismore.",
      causeOfOutage: "Node hardware failure",
      totalAffected: 200,
      outageTimeline: [
        {
          status: "Outage identified",
          time: "2025-07-15T08:00:00Z",
          stage: "stage-1",
          severity: "significant",
          consumers: 200,
        },
        {
          status: "Outage update issued",
          time: "2025-07-15T12:00:00Z",
          stage: "stage-2",
          severity: "significant",
          affected: 50,
          commsCompliance: [
            { channel: "Email comms", time: "2025-07-15T12:05:00Z", complete: true },
            { channel: "SMS comms", time: "2025-07-15T12:10:00Z", complete: true },
            { channel: "Spatial Buzz", time: "2025-07-15T12:15:00Z", complete: true },
            { channel: "ServiceNow", time: "2025-07-15T12:20:00Z", complete: true },
          ],
        },
        {
          status: "Outage resolved",
          time: "2025-07-16T07:00:00Z",
          stage: "Resolved",
          severity: "",
          affected: 0,
        },
      ],
    },
  ],
  COMMS_RECORDS: [
    {
      customerId: "CU100001",
      incidentId: "INC100001",
      channel: "SMS",
      sentAt: "2025-10-10T03:20:00Z",
      region: "Sydney, NSW",
      status: "Sent",
    },
    {
      customerId: "CU100002",
      incidentId: "INC100002",
      channel: "Email",
      sentAt: "2025-09-28T14:35:00Z",
      region: "Melbourne, VIC",
      status: "Sent",
    },
    {
      customerId: "CU100003",
      incidentId: "INC100003",
      channel: "SMS",
      sentAt: "2025-10-14T06:50:00Z",
      region: "Brisbane, QLD",
      status: "Delivered",
    },
    {
      customerId: "CU100004",
      incidentId: "INC100004",
      channel: "Email",
      sentAt: "2025-09-20T11:10:00Z",
      region: "Perth, WA",
      status: "Sent",
    },
    {
      customerId: "CU100005",
      incidentId: "INC100005",
      channel: "SMS",
      sentAt: "2025-10-13T04:05:00Z",
      region: "Adelaide, SA",
      status: "Sent",
    },
    {
      customerId: "CU100006",
      incidentId: "INC100006",
      channel: "Email",
      sentAt: "2025-09-15T07:35:00Z",
      region: "Hobart, TAS",
      status: "Sent",
    },
    {
      customerId: "CU100007",
      incidentId: "INC100007",
      channel: "SMS",
      sentAt: "2025-10-15T05:05:00Z",
      region: "Canberra, ACT",
      status: "Pending",
    },
    {
      customerId: "CU100008",
      incidentId: "INC100008",
      channel: "Email",
      sentAt: "2025-09-10T09:10:00Z",
      region: "Gold Coast, QLD",
      status: "Sent",
    },
    {
      customerId: "CU100009",
      incidentId: "INC100009",
      channel: "SMS",
      sentAt: "2025-10-12T02:10:00Z",
      region: "Darwin, NT",
      status: "Sent",
    },
    {
      customerId: "CU100010",
      incidentId: "INC100010",
      channel: "Email",
      sentAt: "2025-09-05T13:10:00Z",
      region: "Wollongong, NSW",
      status: "Delivered",
    },
    {
      customerId: "CU100011",
      incidentId: "INC100011",
      channel: "SMS",
      sentAt: "2025-10-14T07:35:00Z",
      region: "Newcastle, NSW",
      status: "Sent",
    },
    {
      customerId: "CU100012",
      incidentId: "INC100012",
      channel: "Email",
      sentAt: "2025-09-01T10:10:00Z",
      region: "Geelong, VIC",
      status: "Sent",
    },
    {
      customerId: "CU100013",
      incidentId: "INC100013",
      channel: "SMS",
      sentAt: "2025-10-13T03:05:00Z",
      region: "Ballarat, VIC",
      status: "Sent",
    },
    {
      customerId: "CU100014",
      incidentId: "INC100014",
      channel: "Email",
      sentAt: "2025-08-25T11:05:00Z",
      region: "Cairns, QLD",
      status: "Missed",
    },
    {
      customerId: "CU100015",
      incidentId: "INC100015",
      channel: "SMS",
      sentAt: "2025-10-15T06:05:00Z",
      region: "Toowoomba, QLD",
      status: "Pending",
    },
    {
      customerId: "CU100016",
      incidentId: "INC100016",
      channel: "Email",
      sentAt: "2025-08-20T10:05:00Z",
      region: "Shepparton, VIC",
      status: "Sent",
    },
    {
      customerId: "CU100017",
      incidentId: "INC100017",
      channel: "SMS",
      sentAt: "2025-10-13T02:05:00Z",
      region: "Mackay, QLD",
      status: "Sent",
    },
    {
      customerId: "CU100018",
      incidentId: "INC100018",
      channel: "Email",
      sentAt: "2025-08-15T09:05:00Z",
      region: "Rockhampton, QLD",
      status: "Sent",
    },
    {
      customerId: "CU100019",
      incidentId: "INC100019",
      channel: "SMS",
      sentAt: "2025-10-15T07:05:00Z",
      region: "Bendigo, VIC",
      status: "Sent",
    },
    {
      customerId: "CU100020",
      incidentId: "INC100020",
      channel: "Email",
      sentAt: "2025-08-10T08:05:00Z",
      region: "Sunshine Coast, QLD",
      status: "Delivered",
    },
    {
      customerId: "CU100021",
      incidentId: "INC100021",
      channel: "SMS",
      sentAt: "2025-10-12T01:05:00Z",
      region: "Launceston, TAS",
      status: "Sent",
    },
    {
      customerId: "CU100022",
      incidentId: "INC100022",
      channel: "Email",
      sentAt: "2025-08-05T10:05:00Z",
      region: "Port Macquarie, NSW",
      status: "Sent",
    },
    {
      customerId: "CU100023",
      incidentId: "INC100023",
      channel: "SMS",
      sentAt: "2025-10-15T08:05:00Z",
      region: "Bathurst, NSW",
      status: "Missed",
    },
    {
      customerId: "CU100024",
      incidentId: "INC100024",
      channel: "Email",
      sentAt: "2025-08-01T09:05:00Z",
      region: "Orange, NSW",
      status: "Sent",
    },
    {
      customerId: "CU100025",
      incidentId: "INC100025",
      channel: "SMS",
      sentAt: "2025-10-13T01:05:00Z",
      region: "Dubbo, NSW",
      status: "Sent",
    },
    {
      customerId: "CU100026",
      incidentId: "INC100026",
      channel: "Email",
      sentAt: "2025-07-25T10:05:00Z",
      region: "Wagga Wagga, NSW",
      status: "Sent",
    },
    {
      customerId: "CU100027",
      incidentId: "INC100027",
      channel: "SMS",
      sentAt: "2025-10-15T09:05:00Z",
      region: "Mildura, VIC",
      status: "Pending",
    },
    {
      customerId: "CU100028",
      incidentId: "INC100028",
      channel: "Email",
      sentAt: "2025-07-20T09:05:00Z",
      region: "Albury, NSW",
      status: "Sent",
    },
    {
      customerId: "CU100029",
      incidentId: "INC100029",
      channel: "SMS",
      sentAt: "2025-10-13T00:05:00Z",
      region: "Nowra, NSW",
      status: "Sent",
    },
    {
      customerId: "CU100030",
      incidentId: "INC100030",
      channel: "Email",
      sentAt: "2025-07-15T08:05:00Z",
      region: "Lismore, NSW",
      status: "Delivered",
    },
  ],
};

// OUTAGES
// {
//   incidentId: "", // INCXXXXX
//   communicationId: "", // COMXXXXX
//   status: "", // Active | Resolved
//   type: "", // new-outages | major-outages | significant-outages | exceeding-slo-sla
//   severity: "", // major | significant
//   stage: "", // stage-1 | stage-2 | resolved
//   region: "", // City, State
//   identifiedAt: "", // ISO Date format
//   lastUpdate: "", // ISO Date format
//   title: "",
//   description: "",
//   causeOfOutage: "",
//   totalAffected: 0,
//   outageTimeline: [
//     {
//       status: "Outage identified",
//       time: "", // ISO Date format
//       stage: "", // stage-1 | stage-2 | resolved
//       severity: "", // major | significant
//       consumers: 0,
//     },
//     {
//       status: "Outage update issued",
//       time: "", // ISO Date format
//       stage: "", // stage-1 | stage-2 | resolved
//       severity: "", // major | significant
//       affected: 0,
//       commsCompliance:[
//         {
//           channel: "Email comms",
//           time: "", // ISO Date format
//           complete: null // Boolean
//         },
//         {
//           channel: "SMS comms",
//           time: "", // ISO Date format
//           complete: null // Boolean
//         },
//         {
//           channel: "Spatial Buzz",
//           time: "", // ISO Date format
//           complete: null // Boolean
//         },
//         {
//           channel: "ServiceNow",
//           time: "", // ISO Date format
//           complete: null // Booleane
//         }
//       ]
//     },
//     {
//       status: "Outage resolved",
//       time: "", // ISO Date format
//       stage: "Resolved",
//       severity: "",
//       affected: 0
//     },
//   ]
// }

// COMMS_RECORDS
// {
//   customerId: "", // CUXXXXXX
//   incidentId: "", // INCXXXXX
//   channel: "", // SMS | Email
//   sentAt: "",  // ISO Date format
//   region: "", // City, State
//   status: "", // Sent | Missed | Pending | Delivered
// }
