export const DUMMY_CONSTANTS = {
  LAST_UPDATED: "2025-08-07T00:00:00Z",
  ACMA_OUTAGES: 3120,
  ONGOING_ACMA_OUTAGES: 15,
  UNPLANNED_OUTAGES: 139012,
  OUTAGES: [
    {
      incidentId: "INC102934",
      title: "Core router failure",
      type: "exceeding-slo-sla",
      severity: "major",
      stage: "resolved",
      identifiedAt: "2025-06-17T01:00:49Z",
      totalAffected: 1200,
      region: "Liverpool, NSW",
      causeOfOutage: "Under investigation",
      status: "Resolved",
    },
    {
      incidentId: "INC204853",
      title: "Fiber cut in CBD",
      type: "exceeding-slo-sla",
      severity: "significant",
      stage: "stage-1",
      identifiedAt: "2025-07-17T01:00:49Z",
      totalAffected: 3500,
      region: "Sydney CBD, NSW",
      causeOfOutage: "Fibre network issue",
      status: "Active",
    },
    {
      incidentId: "INC305765",
      title: "Data center cooling failure",
      type: "exceeding-slo-sla",
      severity: "major",
      stage: "stage-1",
      identifiedAt: "2025-08-18T02:00:12Z",
      totalAffected: 5000,
      region: "Melbourne, VIC",
      causeOfOutage: "Data center outage",
      status: "Active",
    },
    {
      incidentId: "INC406876",
      title: "Server rack fire",
      type: "exceeding-slo-sla",
      severity: "major",
      stage: "resolved",
      identifiedAt: "2025-09-18T03:15:45Z",
      totalAffected: 2000,
      region: "Brisbane, QLD",
      causeOfOutage: "Server failure",
      status: "Resolved",
    },
    {
      incidentId: "INC507987",
      title: "WAN latency spike",
      type: "exceeding-slo-sla",
      severity: "significant",
      stage: "stage-1",
      identifiedAt: "2025-09-19T04:20:37Z",
      totalAffected: 300,
      region: "Perth, WA",
      causeOfOutage: "Network latency",
      status: "Active",
    },
    {
      incidentId: "INC608097",
      title: "Perth Suburbs Fiber Cut",
      type: "exceeding-slo-sla",
      severity: "major",
      stage: "stage-1",
      identifiedAt: "2025-05-07T05:15:00Z",
      totalAffected: 22000,
      region: "Perth, WA",
      causeOfOutage: "Network latency",
      status: "Active",
    },
    {
      incidentId: "INC102934",
      title: "Core router failure",
      type: "major-outages",
      severity: "major",
      stage: "resolved",
      identifiedAt: "2025-06-17T01:00:49Z",
      totalAffected: 1200,
      region: "Liverpool, NSW",
      causeOfOutage: "Under investigation",
      status: "Resolved",
    },
    {
      incidentId: "INC204853",
      title: "Fiber cut in CBD",
      type: "significant-outages",
      severity: "significant",
      stage: "stage-1",
      identifiedAt: "2025-07-17T01:00:49Z",
      totalAffected: 3500,
      region: "Sydney CBD, NSW",
      causeOfOutage: "Fibre network issue",
      status: "Active",
    },
    {
      incidentId: "INC204854",
      title: "Ballina exchange issue",
      type: "new-outage",
      severity: "major",
      stage: "stage-2",
      identifiedAt: "2025-07-17T01:00:49Z",
      totalAffected: 900,
      region: "Ballina, NSW",
      causeOfOutage: "Fibre network issue",
      status: "Active",
    },
    {
      incidentId: "INC305765",
      title: "Data center cooling failure",
      type: "major-outages",
      severity: "major",
      stage: "stage-1",
      identifiedAt: "2025-08-18T02:00:12Z",
      totalAffected: 5000,
      region: "Melbourne, VIC",
      causeOfOutage: "Data center outage",
      status: "Active",
    },
    {
      incidentId: "INC406876",
      title: "Server rack fire",
      type: "major-outages",
      severity: "major",
      stage: "resolved",
      identifiedAt: "2025-09-18T03:15:45Z",
      totalAffected: 2000,
      region: "Brisbane, QLD",
      causeOfOutage: "Server failure",
      status: "Resolved",
    },
    {
      incidentId: "INC507987",
      title: "WAN latency spike",
      type: "minor-outages",
      severity: "significant",
      stage: "stage-1",
      identifiedAt: "2025-09-19T04:20:37Z",
      totalAffected: 300,
      region: "Perth, WA",
      causeOfOutage: "Network latency",
      status: "Active",
    },
    {
      incidentId: "INC608098",
      title: "Firewall breach",
      type: "significant-outages",
      severity: "significant",
      stage: "resolved",
      identifiedAt: "2025-09-20T05:30:20Z",
      totalAffected: 800,
      region: "Canberra, ACT",
      causeOfOutage: "Security breach",
      status: "Resolved",
    },
    {
      incidentId: "INC709209",
      title: "Transformer failure",
      type: "critical-outages",
      severity: "major",
      stage: "stage-2",
      identifiedAt: "2025-10-21T06:45:50Z",
      totalAffected: 1500,
      region: "Hobart, TAS",
      causeOfOutage: "Power outage",
      status: "Active",
    },
    {
      incidentId: "INC810320",
      title: "Cloud service downtime",
      type: "major-outages",
      severity: "major",
      stage: "stage-1",
      identifiedAt: "2025-10-22T07:55:10Z",
      totalAffected: 2100,
      region: "Gold Coast, QLD",
      causeOfOutage: "Application downtime",
      status: "Active",
    },
    {
      incidentId: "INC911421",
      title: "User authentication bug",
      type: "minor-outages",
      severity: "significant",
      stage: "resolved",
      identifiedAt: "2025-11-23T08:30:00Z",
      totalAffected: 400,
      region: "Adelaide, SA",
      causeOfOutage: "User access issue",
      status: "Resolved",
    },
    {
      incidentId: "INC100001",
      title: "DNS server outage",
      type: "major-outages",
      severity: "major",
      stage: "stage-2",
      identifiedAt: "2025-06-10T11:00:00Z",
      totalAffected: 3200,
      region: "Darwin, NT",
      causeOfOutage: "DNS failure",
      status: "Active",
    },
    {
      incidentId: "INC100002",
      title: "Switchboard malfunction",
      type: "minor-outages",
      severity: "significant",
      stage: "stage-1",
      identifiedAt: "2025-06-12T13:30:00Z",
      totalAffected: 600,
      region: "Wollongong, NSW",
      causeOfOutage: "Hardware failure",
      status: "Resolved",
    },
    {
      incidentId: "INC100003",
      title: "ISP upstream issue",
      type: "significant-outages",
      severity: "major",
      stage: "stage-2",
      identifiedAt: "2025-06-15T09:45:00Z",
      totalAffected: 2100,
      region: "Geelong, VIC",
      causeOfOutage: "Upstream provider",
      status: "Active",
    },
    {
      incidentId: "INC100004",
      title: "Fiber break at main junction",
      type: "major-outages",
      severity: "significant",
      stage: "stage-1",
      identifiedAt: "2025-06-18T17:20:00Z",
      totalAffected: 5000,
      region: "Townsville, QLD",
      causeOfOutage: "Fiber break",
      status: "Active",
    },
    {
      incidentId: "INC100005",
      title: "Power supply instability",
      type: "critical-outages",
      severity: "major",
      stage: "stage-2",
      identifiedAt: "2025-06-20T21:10:00Z",
      totalAffected: 1800,
      region: "Newcastle, NSW",
      causeOfOutage: "Power instability",
      status: "Resolved",
    },
    {
      incidentId: "INC100006",
      title: "Wireless AP failure",
      type: "minor-outages",
      severity: "significant",
      stage: "stage-1",
      identifiedAt: "2025-06-22T08:00:00Z",
      totalAffected: 250,
      region: "Sunshine Coast, QLD",
      causeOfOutage: "AP hardware",
      status: "Active",
    },
    {
      incidentId: "INC100007",
      title: "Cable cut by construction",
      type: "major-outages",
      severity: "significant",
      stage: "stage-2",
      identifiedAt: "2025-06-25T14:30:00Z",
      totalAffected: 4100,
      region: "Launceston, TAS",
      causeOfOutage: "Construction accident",
      status: "Active",
    },
    {
      incidentId: "INC100008",
      title: "DDoS attack mitigation",
      type: "significant-outages",
      severity: "significant",
      stage: "stage-1",
      identifiedAt: "2025-06-27T16:45:00Z",
      totalAffected: 3700,
      region: "Bendigo, VIC",
      causeOfOutage: "DDoS attack",
      status: "Resolved",
    },
    {
      incidentId: "INC100009",
      title: "Cooling system alert",
      type: "minor-outages",
      severity: "significant",
      stage: "stage-1",
      identifiedAt: "2025-07-01T10:15:00Z",
      totalAffected: 150,
      region: "Cairns, QLD",
      causeOfOutage: "Cooling system",
      status: "Active",
    },
    {
      incidentId: "INC100010",
      title: "Router firmware bug",
      type: "significant-outages",
      severity: "significant",
      stage: "stage-2",
      identifiedAt: "2025-07-03T12:00:00Z",
      totalAffected: 1100,
      region: "Toowoomba, QLD",
      causeOfOutage: "Firmware bug",
      status: "Active",
    },
    {
      incidentId: "INC100011",
      title: "Flooded exchange",
      type: "new-outage",
      severity: "major",
      stage: "stage-2",
      identifiedAt: "2025-07-05T18:30:00Z",
      totalAffected: 2900,
      region: "Ballarat, VIC",
      causeOfOutage: "Flood",
      status: "Resolved",
    },
    {
      incidentId: "INC100012",
      title: "Scheduled upgrade",
      type: "new-outages",
      severity: "significant",
      stage: "stage-1",
      identifiedAt: "2025-07-08T09:00:00Z",
      totalAffected: 700,
      region: "Albury, NSW",
      causeOfOutage: "Scheduled maintenance",
      status: "Active",
    },
    {
      incidentId: "INC100013",
      title: "Switch failure",
      type: "minor-outages",
      severity: "significant",
      stage: "stage-1",
      identifiedAt: "2025-07-10T15:10:00Z",
      totalAffected: 350,
      region: "Rockhampton, QLD",
      causeOfOutage: "Switch hardware",
      status: "Active",
    },
    {
      incidentId: "INC100014",
      title: "Authentication server down",
      type: "significant-outages",
      severity: "major",
      stage: "stage-2",
      identifiedAt: "2025-07-12T17:40:00Z",
      totalAffected: 2100,
      region: "Mackay, QLD",
      causeOfOutage: "Server crash",
      status: "Resolved",
    },
    {
      incidentId: "INC100015",
      title: "Fiber cut at bridge",
      type: "major-outages",
      severity: "major",
      stage: "stage-1",
      identifiedAt: "2025-07-15T20:00:00Z",
      totalAffected: 4200,
      region: "Wagga Wagga, NSW",
      causeOfOutage: "Bridge construction",
      status: "Active",
    },
    {
      incidentId: "INC100016",
      title: "Firewall misconfiguration",
      type: "critical-outages",
      severity: "major",
      stage: "stage-2",
      identifiedAt: "2025-07-18T22:30:00Z",
      totalAffected: 1300,
      region: "Shepparton, VIC",
      causeOfOutage: "Config error",
      status: "Active",
    },
    {
      incidentId: "INC100017",
      title: "ISP routing issue",
      type: "significant-outages",
      severity: "major",
      stage: "stage-1",
      identifiedAt: "2025-07-20T11:00:00Z",
      totalAffected: 1700,
      region: "Mildura, VIC",
      causeOfOutage: "ISP routing",
      status: "Resolved",
    },
    {
      incidentId: "INC100018",
      title: "Power grid failure",
      type: "major-outages",
      severity: "significant",
      stage: "stage-2",
      identifiedAt: "2025-07-23T13:30:00Z",
      totalAffected: 3900,
      region: "Port Macquarie, NSW",
      causeOfOutage: "Grid failure",
      status: "Active",
    },
    {
      incidentId: "INC100019",
      title: "Exchange fire alarm",
      type: "minor-outages",
      severity: "significant",
      stage: "stage-1",
      identifiedAt: "2025-07-25T16:00:00Z",
      totalAffected: 200,
      region: "Bathurst, NSW",
      causeOfOutage: "Fire alarm",
      status: "Active",
    },
    {
      incidentId: "INC100020",
      title: "Cooling plant outage",
      type: "significant-outages",
      severity: "significant",
      stage: "stage-2",
      identifiedAt: "2025-07-28T18:30:00Z",
      totalAffected: 800,
      region: "Orange, NSW",
      causeOfOutage: "Cooling plant",
      status: "Resolved",
    },
    {
      incidentId: "INC100021",
      title: "Main router reboot",
      type: "major-outages",
      severity: "significant",
      stage: "stage-1",
      identifiedAt: "2025-07-30T21:00:00Z",
      totalAffected: 2600,
      region: "Dubbo, NSW",
      causeOfOutage: "Router reboot",
      status: "Active",
    },
  ],
  COMMS_RECORDS: [
    {
      customerId: "CU123402",
      outageId: "INC102934", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "SMS V1.0",
      templateLink: "#",
      sentAt: "2025-06-17T01:00:49Z",
      region: "Liverpool, NSW",
      status: "Sent",
    },
    {
      customerId: "CU32048",
      outageId: "INC204854", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V1.3",
      templateLink: "#",
      sentAt: "2025-06-17T01:00:49Z",
      region: "Ballina, NSW",
      status: "Sent",
    },
    {
      customerId: "CU987654",
      outageId: "INC305765", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "SMS V2.0",
      templateLink: "#",
      sentAt: "2025-06-18T02:15:30Z",
      region: "Sydney, NSW",
      status: "Delivered",
    },
    {
      customerId: "CU543216",
      outageId: "INC406876", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "SMS V1.1",
      templateLink: "#",
      sentAt: "2025-06-18T02:45:12Z",
      region: "Melbourne, VIC",
      status: "Pending",
    },
    {
      customerId: "CU432198",
      outageId: "INC507987", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "Chat V2.2",
      templateLink: "#",
      sentAt: "2025-06-19T03:00:55Z",
      region: "Brisbane, QLD",
      status: "Sent",
    },
    {
      customerId: "CU876543",
      outageId: "INC608097", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V1.5",
      templateLink: "#",
      sentAt: "2025-06-19T04:00:12Z",
      region: "Perth, WA",
      status: "Missed",
    },
    {
      customerId: "CU123456",
      outageId: "INC608098", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V1.0",
      templateLink: "#",
      sentAt: "2025-06-20T05:15:45Z",
      region: "Canberra, ACT",
      status: "Completed",
    },
    {
      customerId: "CU654321",
      outageId: "INC709209", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V1.2",
      templateLink: "#",
      sentAt: "2025-06-20T05:45:30Z",
      region: "Adelaide, SA",
      status: "Sent",
    },
    {
      customerId: "CU789012",
      outageId: "INC810320", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V1.0",
      templateLink: "#",
      sentAt: "2025-06-21T06:30:10Z",
      region: "Hobart, TAS",
      status: "Sent",
    },
    {
      customerId: "CU234567",
      outageId: "INC911421", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "SMS V2.1",
      templateLink: "#",
      sentAt: "2025-06-22T07:10:00Z",
      region: "Darwin, NT",
      status: "Sent",
    },
    {
      customerId: "CU345678",
      outageId: "INC100001", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V1.4",
      templateLink: "#",
      sentAt: "2025-06-22T08:20:00Z",
      region: "Wollongong, NSW",
      status: "Pending",
    },
    {
      customerId: "CU456789",
      outageId: "INC100002", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "SMS V2.2",
      templateLink: "#",
      sentAt: "2025-06-23T09:30:00Z",
      region: "Geelong, VIC",
      status: "Sent",
    },
    {
      customerId: "CU567890",
      outageId: "INC100003", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V1.6",
      templateLink: "#",
      sentAt: "2025-06-23T10:40:00Z",
      region: "Townsville, QLD",
      status: "Missed",
    },
    {
      customerId: "CU678901",
      outageId: "INC100004", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "SMS V1.3",
      templateLink: "#",
      sentAt: "2025-06-24T11:50:00Z",
      region: "Newcastle, NSW",
      status: "Delivered",
    },
    {
      customerId: "CU789123",
      outageId: "INC100005", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V1.7",
      templateLink: "#",
      sentAt: "2025-06-24T12:00:00Z",
      region: "Sunshine Coast, QLD",
      status: "Completed",
    },
    {
      customerId: "CU891234",
      outageId: "INC100006", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "SMS V2.3",
      templateLink: "#",
      sentAt: "2025-06-25T13:10:00Z",
      region: "Launceston, TAS",
      status: "Sent",
    },
    {
      customerId: "CU912345",
      outageId: "INC100007", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V1.8",
      templateLink: "#",
      sentAt: "2025-06-25T14:20:00Z",
      region: "Bendigo, VIC",
      status: "Sent",
    },
    {
      customerId: "CU102345",
      outageId: "INC100008", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "SMS V1.4",
      templateLink: "#",
      sentAt: "2025-06-26T15:30:00Z",
      region: "Cairns, QLD",
      status: "Pending",
    },
    {
      customerId: "CU112345",
      outageId: "INC100009", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V1.9",
      templateLink: "#",
      sentAt: "2025-06-26T16:40:00Z",
      region: "Toowoomba, QLD",
      status: "Sent",
    },
    {
      customerId: "CU122345",
      outageId: "INC100010", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "SMS V2.4",
      templateLink: "#",
      sentAt: "2025-06-27T17:50:00Z",
      region: "Ballarat, VIC",
      status: "Missed",
    },
    {
      customerId: "CU132345",
      outageId: "INC100011", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V2.0",
      templateLink: "#",
      sentAt: "2025-06-27T18:00:00Z",
      region: "Albury, NSW",
      status: "Sent",
    },
    {
      customerId: "CU142345",
      outageId: "INC100012", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "SMS V1.5",
      templateLink: "#",
      sentAt: "2025-06-28T19:10:00Z",
      region: "Rockhampton, QLD",
      status: "Completed",
    },
    {
      customerId: "CU152345",
      outageId: "INC100013", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V2.1",
      templateLink: "#",
      sentAt: "2025-06-28T20:20:00Z",
      region: "Mackay, QLD",
      status: "Sent",
    },
    {
      customerId: "CU162345",
      outageId: "INC100014", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "SMS V2.5",
      templateLink: "#",
      sentAt: "2025-06-29T21:30:00Z",
      region: "Wagga Wagga, NSW",
      status: "Sent",
    },
    {
      customerId: "CU172345",
      outageId: "INC100015", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V2.2",
      templateLink: "#",
      sentAt: "2025-06-29T22:40:00Z",
      region: "Shepparton, VIC",
      status: "Pending",
    },
    {
      customerId: "CU182345",
      outageId: "INC100016", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "SMS V1.6",
      templateLink: "#",
      sentAt: "2025-06-30T23:50:00Z",
      region: "Mildura, VIC",
      status: "Sent",
    },
    {
      customerId: "CU192345",
      outageId: "INC100017", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V2.3",
      templateLink: "#",
      sentAt: "2025-07-01T00:00:00Z",
      region: "Port Macquarie, NSW",
      status: "Missed",
    },
    {
      customerId: "CU202345",
      outageId: "INC100018", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "SMS V2.6",
      templateLink: "#",
      sentAt: "2025-07-01T01:10:00Z",
      region: "Bathurst, NSW",
      status: "Delivered",
    },
    {
      customerId: "CU212345",
      outageId: "INC100019", // matches OUTAGES.incidentId
      channel: "Email",
      templateUsed: "Email V2.4",
      templateLink: "#",
      sentAt: "2025-07-01T02:20:00Z",
      region: "Orange, NSW",
      status: "Sent",
    },
    {
      customerId: "CU222345",
      outageId: "INC100020", // matches OUTAGES.incidentId
      channel: "SMS",
      templateUsed: "SMS V1.7",
      templateLink: "#",
      sentAt: "2025-07-01T03:30:00Z",
      region: "Dubbo, NSW",
      status: "Completed",
    },
  ],
};
